version: "3.8"

services:
  server:
    build:
      context: .
      args:
        ALPINE_TAG: '3.19'
    ports:
      - 8000:8000
    volumes:
      - './config:/config'
    environment:
      FLASK_RUN_DEBUG: 1
      FLASK_RUN_HOST: '0.0.0.0'
      FLASK_RUN_PORT: 8000  # Same as Gunicorn
    entrypoint: ['flask', 'run']
