name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run flake8
        run: flake8
      - name: Run isort
        run: isort --check --diff .
